Upgrade to sailor 2.6.18
elasticio/mailchimp-component pull request #16
Opened 2020-10-27 13:02 UTC by denyshld

2020-10-30 09:34 UTC, shulkaolka requested changes

2020-10-30 09:34 UTC, shulkaolka commented on CHANGELOG.md
> +* Upgrade to sailor 2.6.18
```suggestion
* Upgrade to sailor 2.6.18
* Annual audit of the component code to check if it exposes a sensitive data in the logs
```

2020-10-30 09:34 UTC, shulkaolka commented on circle.yml
> +      - image: circleci/node:12-stretch
```suggestion
      - image: circleci/node:14-stretch
```

2020-10-30 09:34 UTC, shulkaolka commented on lib/actions/unsubscribe.js
> +        self.logger.info('Received response');
```suggestion
        self.logger.info('Response received');
```

2020-10-30 09:34 UTC, shulkaolka commented on lib/actions/unsubscribe.js
> +        self.logger.error('Error occured');
```suggestion
        self.logger.error('Error occurred');
```

2020-10-30 09:34 UTC, shulkaolka commented on lib/actions/upsertCustomer.js
> +        self.logger.info('Received response');
```suggestion
        self.logger.info('Response received');
```

2020-10-30 09:34 UTC, shulkaolka commented on lib/actions/upsertCustomer.js
> +        self.logger.error('Error occured');
```suggestion
        self.logger.error('Error occurred');
```

2020-10-30 09:34 UTC, shulkaolka commented on package.json
> +    "node": ">=12.13.0"
Maybe v14 will be better?

2020-11-02 10:03 UTC, shulkaolka approved these changes

2020-11-05 11:42 UTC, shulkaolka requested changes

2020-11-05 11:42 UTC, shulkaolka commented on CHANGELOG.md
> +
```suggestion
* Annual npm vulnerabilities audit

```

2020-11-05 11:42 UTC, shulkaolka commented on lib/actions/subscribe.js
> +    this.emit('data', messages.newMessageWithBody(response));
```suggestion
    await this.emit('data', messages.newMessageWithBody(response));
```

2020-11-05 11:42 UTC, shulkaolka commented on lib/actions/unsubscribe.js
> +    this.emit('data', messages.newMessageWithBody(response));
```suggestion
    await this.emit('data', messages.newMessageWithBody(response));
```

2020-11-05 11:42 UTC, shulkaolka commented on lib/actions/upsertCustomer.js
> +    this.emit('data', messages.newMessageWithBody(response));
```suggestion
    await this.emit('data', messages.newMessageWithBody(response));
```

2020-11-05 11:42 UTC, shulkaolka commented on package.json
> +    "node": ">=14"
```suggestion
    "node": "14"
```

2020-11-05 12:41 UTC, shulkaolka approved these changes

2020-11-05 13:12 UTC, A3a3e1 approved these changes

2020-11-06 14:54 UTC, merged